meta_product_name: "Cashless 386"
meta_title: "Cashless 386 - Pay anywhere with your phone"
meta_description: "Pay cashless in shops, flea markets, and your favorite restaurant in Berlin! Download Cashless 386 now and get 10% off for your next purchase!"
meta_type: "Payment App"
meta_url: "www.cashless-386.xyz"
meta_image: "logo-og.png" # should exist in `app/assets/images/`
